import { z } from 'zod';

/**
 * User validation schemas using Zod (infrastructure).
 * Same as example-react.
 */
export const UserSchema = z.object({
  id: z.string().min(1, 'ID is required'),
  name: z
    .string()
    .min(2, 'Name must be at least 2 characters')
    .max(100, 'Name must be less than 100 characters')
    .trim(),
  email: z
    .string()
    .email('Invalid email format')
    .toLowerCase()
    .trim(),
});

/** Schema for creating a user (ID is generated by repository) */
export const CreateUserSchema = UserSchema.omit({ id: true });

export type UserSchemaType = z.infer<typeof UserSchema>;
export type CreateUserSchemaType = z.infer<typeof CreateUserSchema>;
