import type { User } from './user.entities';

/**
 * Domain validation contracts (no external libraries).
 * Validation rules: name 2–100 chars, valid email format.
 * Actual schema implementation (e.g. Zod) lives in infrastructure.
 */

/** Full user shape used for validation */
export type UserInput = User;

/** Input for creating a user (ID is generated by the system) */
export type CreateUserInput = Omit<User, 'id'>;
