import type { User } from './user.entities';

/** Full user shape used for validation */
export type UserInput = User;

/** Input for creating a user (ID is generated by the system) */
export type CreateUserInput = Omit<User, 'id'>;
